title:            Ed Blackburn
tagline:          Software Development
description:      This blog is a series of articles about my journey as a software developer. Lessons I've learned earnestly through experience and new lessons I learn day by day as I strive to continuously improve as a professional.
canonical: http://ejb.name

# Owner/author information
owner:
  name:           Ed Blackburn
  avatar:         avatar.png
  bio:            "Software Dev"
  email:          ed@ejb.name
  twitter:        ejblackburn
  github:         edblackburn
  instagram:      edblackburn
  disqus:         Ed_Blackburn
  location:       "Kent, UK"
  # Plug in your disqus shortname!

# Open Graph customization
opengraph:
  locale:           en_GB

# Links to include in top navigation
# For external links add external: true
links:
  - title: Who is Ed?
    url: /about
  - title: Presentations
    url: /presentations
  - title: Hire Me
    url: /hireme    
  - title: Github
    url: https://github.com/edblackburn
    external: true

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/London
future:      true
markdown:    kramdown

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

sass:
    style: :compressed

gems:
  - jekyll-gist    

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   /:categories/:title

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp"]
